# Generated by Django 4.2.16 on 2026-05-30 14:06

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_email', django_cryptography.fields.encrypt(models.EmailField(max_length=254))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('device_type', models.CharField(choices=[('Desktop', 'Desktop PC'), ('Laptop', 'Laptop')], max_length=50)),
                ('installed_date', models.DateField()),
                ('serial_number', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, null=True))),
                ('status', models.CharField(default='Healthy', max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(default='Technician', max_length=50)),
                ('status', models.CharField(default='Active', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicianTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(default='In-house', max_length=50)),
                ('brought_by', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('deadline', models.DateField()),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('issue', models.TextField()),
                ('special_note', django_cryptography.fields.encrypt(models.TextField(blank=True, null=True))),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tasks', to='api.device')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='api.systemuser')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_performed', models.DateField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='api.device')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceHealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hard_drive_health', models.FloatField(help_text='Hard drive health percentage (0-100%)')),
                ('past_failure_attempts', models.IntegerField(default=0, help_text='Number of past crashes/failures')),
                ('repair_history_count', models.IntegerField(default=0, help_text='Total number of times repaired')),
                ('predicted_risk_level', models.CharField(blank=True, choices=[('Low', 'Low Risk'), ('Medium', 'Medium Risk'), ('High', 'High Risk')], max_length=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_logs', to='api.device')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('value', django_cryptography.fields.encrypt(models.CharField(max_length=100))),
                ('status', models.CharField(default='Active', max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='api.company')),
            ],
        ),
    ]
