# Generated by Django 4.2.16 on 2026-06-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_systemuser_is_2fa_enabled_systemuser_totp_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('action', models.TextField()),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Warning', 'Warning'), ('Error', 'Error')], default='Success', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
