# Generated by Django 5.2.15 on 2026-06-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_systemlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='notify_contracts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='notify_security',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='notify_tasks',
            field=models.BooleanField(default=True),
        ),
    ]
